### ISSUE TITLE
feature request: inotify

### ISSUE THREAD

**Issue by xyproto** [Cian911/switchboard#17]
On Linux, manually polling is not needed. Have you looked into inotifywait or something like https://github.com/xyproto/recwatch?

Switchboard is a neat idea!

**Comment by Cian911** [comment]
Hey @xyproto, thanks for taking the time to use switchboard!

Yes, this is something I absolutely will be doing. In Linux, we can get file closed events, which avoids the need for polling altogether.

In the very near future, (potentially the next release) I will be looking to support this, and have polling as a fallback for other OS envs.

Stay tuned!
